package me.fil.texpansion;

public enum EnumToolType 
{
	SWORD, PICKAXE, SHOVEL, AXE, HOE,
	SWICKAXE, SHICKAXE, PICKAXESHOVEL, SHOVELAXE, 
	PICKAXEAXE, SHOVELHOE, AXEHOE, PICKAXEHOE, 
	SWORDAXE, SWORDPICKAXE, SWORDSHOVEL, SWORDHOE;
}
