package me.fil.texpansion;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;
import me.fil.texpansion.ApiManager.API;
import me.fil.texpansion.block.DeathlyTNT;
import me.fil.texpansion.block.Dust;
import me.fil.texpansion.block.Fermentator;
import me.fil.texpansion.block.FermentedLog;
import me.fil.texpansion.block.FermentedWood;
import me.fil.texpansion.block.InfectedQuartz;
import me.fil.texpansion.block.RupifiedOre;
import me.fil.texpansion.item.Fruit;
import me.fil.texpansion.item.Paintbrush;
import me.fil.texpansion.item.RupeeStick;
import me.fil.texpansion.item.RupifiedIngot;
import me.fil.texpansion.item.RupifiedItemShickaxe;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.ThreadDownloadImageData;
import net.minecraft.client.renderer.texture.ITextureObject;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemFood;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.util.EnumHelper;

@Mod(modid = TExpansion.MODID, name = TExpansion.MODID, version = TExpansion.VERSION /*dependencies = "required-after:TConstruct;required-after:IC2;"*/ /*dependencies = "required-after:Forge@[9.11.1.953,);"*/)
public class TExpansion
{
    public static final String MODID = "TExpansion";
    public static final String VERSION = "1.037";
    
    public static Logger logger = Logger.getLogger("TExpansion");
    
    @Instance(value = TExpansion.MODID)
    public static TExpansion instance;
    
    @SidedProxy(clientSide = "me.fil.texpansion.client.ClientProxy", serverSide = "me.fil.texpansion.CommonProxy")
    public static CommonProxy proxy;
    
    //Creative Tab
    public static final CreativeTabs tab = new CreativeTabs("tExpansionTab")
    {
    	public String getTranslatedTabLabel()
    	{
    		return "Thermomic Expansion";
    	}

		@Override
		public Item getTabIconItem() 
		{
			return TExpansion.shickaxeRupified;
		}
    };
    
    //Tool Types
    //public static final EnumToolMaterial RUPIFIED = EnumHelper.addToolMaterial("RUPIFIED", 5, 0, 80F, 300F, 67);
    
    //Blocks
    public static Block fermentator;
    public static Block logFermented;
    public static Block woodFermented;
    public static Block quartzInfected;
    public static Block tntDeathly;
    public static Block blockDust;
    public static Block blender;
    public static Block oreRupified;
    public static Block oreRupee;
    
    //Items
    public static Item waterDirty;
    public static Item raddishHorse;
    public static Item brush;
    public static Item fruit;
    public static Item shickaxeRupified;
    public static Item ingotRupified;
    public static Item ingotRupee;
    public static Item stickRupee;
    
    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
    	ModMetadata meta = event.getModMetadata();
    	
    	meta.name = "Thermomic Expansion";
    	meta.autogenerated = false;
    	List<String> authorList = new ArrayList<String>();
    	authorList.add("Miner_Fil");
    	authorList.add("Miner_Marx");
    	meta.authorList = authorList;
    	meta.credits = "<3 to the mod creators.";
    	meta.url = "http://github.com/TheFil/TExpansion/";
    }
    
    @EventHandler
    public void init(FMLInitializationEvent event)
    {
    	if(Loader.isModLoaded("TConstruct"))
    	{
    		Logger l = Logger.getLogger("TConstruct");
    		logger.info("TConstruct, What shall we be doing tonight?");
    		l.info("TExpansion, We shall take over!");
    	}
    	else if(Loader.isModLoaded("TConstruct") && Loader.isModLoaded("Natura"))
    	{
    		Logger l = Logger.getLogger("TConstruct");
    		Logger n = Logger.getLogger("Natura");
    		logger.info("TConstruct and Natura, What shall we be doing tonight?");
    		l.info("TExpansion, We shall take over!");
    		n.info("^^^^ What that guy said.");
    	}
    	else
    	{
    		logger.info("I guess tonight I might aswell take over myself!");
    	}
    	proxy = new CommonProxy();
    	
    	CommonProxy.removeRecipe(new ItemStack(Blocks.torch, 0));
    	
    	proxy.registerRenderers();
    	
    	EnumManager.Tools.addToolMaterial("RUPIFIED", EnumHelper.addToolMaterial("RUPIFIED", 99, 0, 125F, 11.7F, 67));
    	EnumManager.Tools.addToolMaterial("RUPEE", EnumHelper.addToolMaterial("RUPEE", 5, 9000, 19F, 4.9F, 34));
    	//proxy.registerOreDictionary();
    	
    	//OreDictionary.registerOre("blockDust", blockDust);
    	
    	logFermented = new FermentedLog(Material.wood).setStepSound(Block.soundTypeWood).setBlockName("logFermented").setBlockTextureName("texpansion:log_fermented").setCreativeTab(tab);
    	woodFermented = new FermentedWood(Material.wood).setStepSound(Block.soundTypeWood).setBlockName("woodFermented").setBlockTextureName("texpansion:woodFermented").setCreativeTab(tab);
    	quartzInfected = new InfectedQuartz(Material.iron).setStepSound(Block.soundTypeMetal).setBlockName("quartzInfected").setBlockTextureName("texpansion:quartzInfected").setCreativeTab(tab).setBlockUnbreakable().setResistance(0.0F);
    	tntDeathly = new DeathlyTNT().setBlockName("tntDeathly").setBlockTextureName("texpansion:tntDeathly").setCreativeTab(tab);
    	blockDust = new Dust(Material.sand).setStepSound(Block.soundTypeSand).setBlockName("blockDust").setBlockTextureName("texpansion:dust").setCreativeTab(tab);
    	fermentator = new Fermentator(Material.iron).setStepSound(Block.soundTypeMetal).setBlockName("fermentator").setBlockTextureName("texpansion:fermentator").setCreativeTab(tab);
    	oreRupified = new RupifiedOre(Material.rock).setStepSound(Block.soundTypeStone).setBlockName("oreRupified").setBlockTextureName("texpansion:oreRupified").setCreativeTab(tab);
    	
    	raddishHorse = (new ItemFood(20, 1.5F, false)).setUnlocalizedName("raddishHorse").setTextureName("texpansion:raddishHorse").setCreativeTab(tab);
    	brush = new Paintbrush();
    	fruit = new Fruit();
    	shickaxeRupified = new RupifiedItemShickaxe(EnumManager.Tools.getMaterial("RUPIFIED"), EnumToolType.SHICKAXE).setUnlocalizedName("shickaxeRupified").setTextureName("texpansion:shickaxeRupified").setCreativeTab(tab);
    	ingotRupified = new RupifiedIngot().setUnlocalizedName("ingotRupified").setTextureName("texpansion:ingotRupified").setCreativeTab(tab);
    	stickRupee = new RupeeStick().setUnlocalizedName("stickRupee").setTextureName("texpansion:stickRupee").setCreativeTab(tab);
    	
    	GameRegistry.registerBlock(logFermented, logFermented.getUnlocalizedName());
    	GameRegistry.registerBlock(woodFermented, woodFermented.getUnlocalizedName());
    	GameRegistry.registerBlock(quartzInfected, quartzInfected.getUnlocalizedName());
    	GameRegistry.registerBlock(tntDeathly, tntDeathly.getUnlocalizedName());
    	GameRegistry.registerBlock(blockDust, blockDust.getUnlocalizedName());
    	GameRegistry.registerBlock(fermentator, fermentator.getUnlocalizedName());
    	GameRegistry.registerBlock(oreRupified, oreRupified.getUnlocalizedName());
    	
    	GameRegistry.registerItem(raddishHorse, raddishHorse.getUnlocalizedName());
    	GameRegistry.registerItem(brush, "brush");
    	GameRegistry.registerItem(fruit, "fruit");
    	GameRegistry.registerItem(shickaxeRupified, shickaxeRupified.getUnlocalizedName());
    	GameRegistry.registerItem(ingotRupified, ingotRupified.getUnlocalizedName());
    	GameRegistry.registerItem(stickRupee, stickRupee.getUnlocalizedName());
    	
    	LanguageRegistry.addName(logFermented, "Fermented Log");
    	LanguageRegistry.addName(woodFermented, "Fermented Wood Planks");
    	LanguageRegistry.addName(quartzInfected, "Infected Quartz");
    	LanguageRegistry.addName(tntDeathly, "Deathly TNT");
    	LanguageRegistry.addName(blockDust, "Dust");
    	LanguageRegistry.addName(raddishHorse, "Horse Raddish");
    	LanguageRegistry.addName(fermentator, "Fermentator");
    	LanguageRegistry.addName(shickaxeRupified, "Rupified Shickaxe");
    	LanguageRegistry.addName(oreRupified, "Rupified Ore");
    	LanguageRegistry.addName(ingotRupified, "Rupified Ingot");
    	LanguageRegistry.addName(stickRupee, "Rupee Stick");
    	
    	//for(int i = 0; i < Paintbrush.names.length; i++)
    	for(int i = 0; i < Manager.Names.item_unlocalized_names.get(brush).length; i++)
    		LanguageRegistry.addName(new ItemStack(brush, 1, i), Manager.Names.item_names.get(brush)[i]);
    	for(int i = 0; i < Manager.Names.item_unlocalized_names.get(fruit).length; i++)
    		LanguageRegistry.addName(new ItemStack(fruit, 1, i), Manager.Names.item_names.get(fruit)[i]);

    	shickaxeRupified.setHarvestLevel("pickaxe", 99);
    	shickaxeRupified.setHarvestLevel("shovel", 99);
    	shickaxeRupified.setHarvestLevel("axe", 99);
    	
    	oreRupified.setHarvestLevel("shickaxe", 99);
    	
    	GameRegistry.addShapelessRecipe(new ItemStack(woodFermented, 3), new ItemStack(logFermented));
    	GameRegistry.addShapelessRecipe(new ItemStack(quartzInfected, 1), new ItemStack(Blocks.quartz_block), new ItemStack(Items.rotten_flesh), new ItemStack(Items.rotten_flesh));
    	GameRegistry.addShapelessRecipe(new ItemStack(raddishHorse, 1), new ItemStack(Items.beef), new ItemStack(Items.porkchop), new ItemStack(Items.leather));
    	GameRegistry.addShapelessRecipe(new ItemStack(raddishHorse, 1), new ItemStack(Items.cooked_beef), new ItemStack(Items.cooked_porkchop), new ItemStack(Items.leather));
    	GameRegistry.addShapelessRecipe(new ItemStack(raddishHorse, 1), new ItemStack(Items.beef), new ItemStack(Items.cooked_porkchop), new ItemStack(Items.leather));
    	GameRegistry.addShapelessRecipe(new ItemStack(raddishHorse, 1), new ItemStack(Items.cooked_beef), new ItemStack(Items.porkchop), new ItemStack(Items.leather));
    	GameRegistry.addShapelessRecipe(new ItemStack(stickRupee, 2), new ItemStack(ingotRupified), new ItemStack(ingotRupified));
    	
    	GameRegistry.addRecipe(new ItemStack(shickaxeRupified, 1), "xxx", "dyz", " ya", 'x', new ItemStack(ingotRupified), 'y', new ItemStack(stickRupee), 'd', new ItemStack(Items.diamond_pickaxe), 'z', new ItemStack(Items.diamond_axe), 'a', new ItemStack(Items.diamond_shovel));
    	
    	GameRegistry.addSmelting(oreRupified, new ItemStack(ingotRupified, 1), 4F);
    	
    	GameRegistry.registerWorldGenerator(new OreManager(), 0);
    	
    	addCapes();
    }
    
    @EventHandler
    public void postInit(FMLPostInitializationEvent event)
    {
    	CommonProxy.registerOreDictionary();
    }
    
	  public static void addCapes() {
	    	String apiCapeURL = "http://fil.net63.net/CapesDir/index.php" + ApiManager.getEncryptedApi(API.CAPE);
	    	String ownerCapeURL = "http://fil.net63.net/CapesDir/hardcorerpgcape.png";
	    	//String helperCapeURL = "http://fil.net63.net/hardcorerpghelpcape.png";
	    	//String contribCapeURL = "http://fil.net63.net/hardcorerpgcontribcape.png";
	    	
	    	ThreadDownloadImageData ownerImage = new ThreadDownloadImageData(null, ownerCapeURL, null, null);
	    	
	    	Minecraft.getMinecraft().renderEngine.loadTexture(new ResourceLocation("cloaks/Miner_Fil"), (ITextureObject)ownerImage);
	    	Minecraft.getMinecraft().renderEngine.loadTexture(new ResourceLocation("cloaks/Miner_Marx"), (ITextureObject) ownerImage);
	    }
}
